import type { Product } from '../../domain/types'

/**
 * Demo-Datensatz. Marken und Modelle sind frei erfunden, die Attribute
 * orientieren sich an realen Herstellerangaben fuer Buerodrehstuehle.
 * Im Live-Betrieb liefert der Publisher diese Tabelle aus seinem eigenen Test.
 */
export const products: Product[] = [
  {
    id: 'nordsitz-aeris-300',
    brand: 'Nordsitz',
    model: 'Aeris 300',
    priceEur: 429,
    grade: 1.7,
    listRank: 1,
    tagline: 'Unser Testsieger 2026',
    editorNote:
      'Der ausgewogenste Stuhl im Test. Sauber verarbeitete Synchronmechanik, ehrlicher Preis, keine Schwächen im Alltag – solange man keine Kopfstütze braucht.',
    attrs: {
      material: 'netz',
      heightMinCm: 168,
      heightMaxCm: 195,
      maxLoadKg: 130,
      dailyHoursMax: 9,
      lumbar: 'verstellbar',
      headrest: false,
      armrests: '3D',
      seatDepthAdjust: true,
      mechanism: 'synchro',
      ergoScore: 84,
      warrantyYears: 5,
    },
  },
  {
    id: 'ergolar-vertex-pro',
    brand: 'Ergolar',
    model: 'Vertex Pro',
    priceEur: 689,
    grade: 1.3,
    listRank: 2,
    tagline: 'Beste Ergonomie im Test',
    editorNote:
      'Der Stuhl, auf dem wir selbst sitzen. Alles ist verstellbar, die Lordosenstütze lässt sich exakt auf die eigene Wirbelsäule schieben. Preislich ambitioniert, über die Jahre gerechnet aber fair.',
    attrs: {
      material: 'netz',
      heightMinCm: 165,
      heightMaxCm: 200,
      maxLoadKg: 125,
      dailyHoursMax: 12,
      lumbar: 'verstellbar',
      headrest: true,
      armrests: '4D',
      seatDepthAdjust: true,
      mechanism: 'synchro-plus',
      ergoScore: 92,
      warrantyYears: 8,
    },
  },
  {
    id: 'kernwerk-k7-basic',
    brand: 'Kernwerk',
    model: 'K7 Basic',
    priceEur: 199,
    grade: 2.8,
    listRank: 3,
    tagline: 'Preistipp für gelegentliches Sitzen',
    editorNote:
      'Für den Gäste- oder Zweitschreibtisch völlig in Ordnung. Für einen echten Homeoffice-Arbeitstag ist er es nicht – die Lehne ist starr und die Polster geben nach wenigen Monaten nach.',
    attrs: {
      material: 'polster',
      heightMinCm: 160,
      heightMaxCm: 185,
      maxLoadKg: 110,
      dailyHoursMax: 6,
      lumbar: 'fest',
      headrest: false,
      armrests: '1D',
      seatDepthAdjust: false,
      mechanism: 'wippmechanik',
      ergoScore: 58,
      warrantyYears: 2,
    },
  },
  {
    id: 'vitaform-balance-24',
    brand: 'Vitaform',
    model: 'Balance 24',
    priceEur: 879,
    grade: 1.4,
    tagline: '24-Stunden-Stuhl für Vielsitzer',
    editorNote:
      'Ursprünglich für Leitwarten und Schichtbetrieb entwickelt. Wer zehn Stunden und mehr am Schreibtisch verbringt, merkt den Unterschied am Abend.',
    attrs: {
      material: 'polster',
      heightMinCm: 170,
      heightMaxCm: 200,
      maxLoadKg: 150,
      dailyHoursMax: 24,
      lumbar: 'verstellbar',
      headrest: true,
      armrests: '4D',
      seatDepthAdjust: true,
      mechanism: 'synchro-plus',
      ergoScore: 89,
      warrantyYears: 10,
    },
  },
  {
    id: 'lumbara-flex-s',
    brand: 'Lumbara',
    model: 'Flex S',
    priceEur: 349,
    grade: 1.8,
    tagline: 'Für zierliche und kleinere Personen',
    editorNote:
      'Einer der wenigen guten Stühle, die unter 170 cm wirklich passen. Kürzere Sitzfläche, niedrigere Sitzhöhe – ein Detail, das Standardmodelle regelmäßig verfehlen.',
    attrs: {
      material: 'netz',
      heightMinCm: 152,
      heightMaxCm: 176,
      maxLoadKg: 110,
      dailyHoursMax: 9,
      lumbar: 'verstellbar',
      headrest: false,
      armrests: '3D',
      seatDepthAdjust: true,
      mechanism: 'synchro',
      ergoScore: 82,
      warrantyYears: 5,
    },
  },
  {
    id: 'steelbase-tectum-xl',
    brand: 'Steelbase',
    model: 'Tectum XL',
    priceEur: 749,
    grade: 1.6,
    tagline: 'XXL-Modell bis 180 kg',
    editorNote:
      'Verstärktes Fußkreuz, breitere Sitzfläche, spürbar festere Polster. Für kräftige und große Personen die einzige Empfehlung im Test, die wir ohne Einschränkung aussprechen.',
    attrs: {
      material: 'polster',
      heightMinCm: 175,
      heightMaxCm: 205,
      maxLoadKg: 180,
      dailyHoursMax: 12,
      lumbar: 'verstellbar',
      headrest: true,
      armrests: '4D',
      seatDepthAdjust: true,
      mechanism: 'synchro-plus',
      ergoScore: 86,
      warrantyYears: 6,
    },
  },
  {
    id: 'officio-mesh-one',
    brand: 'Officio',
    model: 'Mesh One',
    priceEur: 279,
    grade: 2.3,
    listRank: 4,
    tagline: 'Beliebter Einstieg mit Netzrücken',
    editorNote:
      'Der meistverkaufte Netzstuhl in dieser Preisklasse. Solide für den halben Arbeitstag, aber die Lordosenstütze ist fest verbaut und die Armlehnen lassen sich nur in der Höhe verstellen.',
    attrs: {
      material: 'netz',
      heightMinCm: 163,
      heightMaxCm: 188,
      maxLoadKg: 100,
      dailyHoursMax: 6,
      lumbar: 'fest',
      headrest: false,
      armrests: '2D',
      seatDepthAdjust: false,
      mechanism: 'synchro',
      ergoScore: 66,
      warrantyYears: 3,
    },
  },
  {
    id: 'aeronis-ergo-500',
    brand: 'Aeronis',
    model: 'Ergo 500',
    priceEur: 549,
    grade: 1.5,
    tagline: 'Bestes Preis-Leistungs-Verhältnis der Oberklasse',
    editorNote:
      'Bietet fast alles, was der Vertex Pro kann, kostet aber 140 € weniger. Die Kopfstütze ist in Höhe und Neigung verstellbar – in dieser Preisklasse keine Selbstverständlichkeit.',
    attrs: {
      material: 'netz',
      heightMinCm: 166,
      heightMaxCm: 192,
      maxLoadKg: 120,
      dailyHoursMax: 10,
      lumbar: 'verstellbar',
      headrest: true,
      armrests: '4D',
      seatDepthAdjust: true,
      mechanism: 'synchro',
      ergoScore: 88,
      warrantyYears: 5,
    },
  },
  {
    id: 'nordsitz-kontur-leder',
    brand: 'Nordsitz',
    model: 'Kontur Leder',
    priceEur: 399,
    grade: 2.5,
    listRank: 5,
    tagline: 'Chefsessel-Optik fürs Videocall-Bild',
    editorNote:
      'Sieht im Videocall gut aus und ist beim Zurücklehnen bequem. Ergonomisch bleibt er Mittelmaß: feste Lordosenstütze, keine Sitztiefenverstellung, Kunstleder wird im Sommer warm.',
    attrs: {
      material: 'kunstleder',
      heightMinCm: 170,
      heightMaxCm: 192,
      maxLoadKg: 120,
      dailyHoursMax: 8,
      lumbar: 'fest',
      headrest: true,
      armrests: '2D',
      seatDepthAdjust: false,
      mechanism: 'synchro',
      ergoScore: 64,
      warrantyYears: 3,
    },
  },
  {
    id: 'kernwerk-aktiv-move',
    brand: 'Kernwerk',
    model: 'Aktiv Move',
    priceEur: 459,
    grade: 1.9,
    tagline: 'Bewegungssitz gegen starres Sitzen',
    editorNote:
      'Bewusst ohne Armlehnen konstruiert. Der Sitz gibt in alle Richtungen nach und zwingt zu ständigen Mikrobewegungen. Gewöhnungsbedürftig, für unruhige Sitzer aber die beste Wahl im Test.',
    attrs: {
      material: 'polster',
      heightMinCm: 160,
      heightMaxCm: 190,
      maxLoadKg: 120,
      dailyHoursMax: 9,
      lumbar: 'verstellbar',
      headrest: false,
      armrests: 'keine',
      seatDepthAdjust: true,
      mechanism: 'aktiv',
      ergoScore: 80,
      warrantyYears: 5,
    },
  },
  {
    id: 'ergolar-home-200',
    brand: 'Ergolar',
    model: 'Home 200',
    priceEur: 249,
    grade: 2.0,
    tagline: 'Der beste Stuhl unter 250 €',
    editorNote:
      'Der kleine Ergolar zeigt, was in dieser Preisklasse möglich ist: verstellbare Lordosenstütze und Sitztiefenverstellung – beides fehlt der Konkurrenz für 250 €.',
    attrs: {
      material: 'netz',
      heightMinCm: 158,
      heightMaxCm: 182,
      maxLoadKg: 110,
      dailyHoursMax: 8,
      lumbar: 'verstellbar',
      headrest: false,
      armrests: '2D',
      seatDepthAdjust: true,
      mechanism: 'synchro',
      ergoScore: 74,
      warrantyYears: 3,
    },
  },
  {
    id: 'vitaform-medic-pro',
    brand: 'Vitaform',
    model: 'Medic Pro',
    priceEur: 1149,
    grade: 1.2,
    tagline: 'Für diagnostizierte Rückenbeschwerden',
    editorNote:
      'Der einzige Stuhl im Test mit einzeln einstellbarer Lordose und Beckenkippung. Teuer, aber bei ärztlich festgestellten Beschwerden die Empfehlung, die wir am häufigsten aussprechen.',
    attrs: {
      material: 'polster',
      heightMinCm: 165,
      heightMaxCm: 198,
      maxLoadKg: 140,
      dailyHoursMax: 12,
      lumbar: 'verstellbar',
      headrest: true,
      armrests: '4D',
      seatDepthAdjust: true,
      mechanism: 'synchro-plus',
      ergoScore: 95,
      warrantyYears: 10,
    },
  },
  {
    id: 'lumbara-kompakt-k',
    brand: 'Lumbara',
    model: 'Kompakt K',
    priceEur: 399,
    grade: 1.8,
    tagline: 'Kleiner Stuhl mit voller Ausstattung',
    editorNote:
      'Der Flex S mit Kopfstütze und etwas mehr Polster. Unter 175 cm ist er für uns die vollständigste Empfehlung im Test – so ausgestattete Modelle gibt es in dieser Größe fast nie.',
    attrs: {
      material: 'netz',
      heightMinCm: 150,
      heightMaxCm: 174,
      maxLoadKg: 110,
      dailyHoursMax: 9,
      lumbar: 'verstellbar',
      headrest: true,
      armrests: '3D',
      seatDepthAdjust: true,
      mechanism: 'synchro',
      ergoScore: 83,
      warrantyYears: 5,
    },
  },
  {
    id: 'officio-home-pro',
    brand: 'Officio',
    model: 'Home Pro',
    priceEur: 229,
    grade: 2.1,
    tagline: 'Unser Preistipp für den ganzen Arbeitstag',
    editorNote:
      'Der günstigste Stuhl im Test, den wir für einen vollen Homeoffice-Tag empfehlen. Verstellbare Lordosenstütze und Sitztiefenverstellung für 229 Euro – dafür ist die Polsterung dünn und die Armlehnen wackeln leicht.',
    attrs: {
      material: 'netz',
      heightMinCm: 158,
      heightMaxCm: 188,
      maxLoadKg: 120,
      dailyHoursMax: 8,
      lumbar: 'verstellbar',
      headrest: false,
      armrests: '2D',
      seatDepthAdjust: true,
      mechanism: 'synchro',
      ergoScore: 72,
      warrantyYears: 3,
    },
  },
  {
    id: 'steelbase-solid-140',
    brand: 'Steelbase',
    model: 'Solid 140',
    priceEur: 489,
    grade: 1.8,
    tagline: 'Kräftig gebaut, ohne XXL-Aufpreis',
    editorNote:
      'Die kleine Ausgabe des Tectum XL. Bis 140 kg freigegeben, deutlich festere Polster als der Rest des Testfelds und trotzdem unter 500 Euro.',
    attrs: {
      material: 'polster',
      heightMinCm: 166,
      heightMaxCm: 196,
      maxLoadKg: 140,
      dailyHoursMax: 10,
      lumbar: 'verstellbar',
      headrest: true,
      armrests: '3D',
      seatDepthAdjust: true,
      mechanism: 'synchro',
      ergoScore: 81,
      warrantyYears: 5,
    },
  },
  {
    id: 'vitaform-ergo-small',
    brand: 'Vitaform',
    model: 'Ergo Small',
    priceEur: 649,
    grade: 1.4,
    tagline: 'Orthopädisch, in kleiner Ausführung',
    editorNote:
      'Die Technik des Medic Pro in einem Gehäuse für Körpergrößen ab 152 cm. Bei Rückenbeschwerden und kleiner Statur die einzige wirklich saubere Lösung im Testfeld.',
    attrs: {
      material: 'polster',
      heightMinCm: 152,
      heightMaxCm: 178,
      maxLoadKg: 140,
      dailyHoursMax: 12,
      lumbar: 'verstellbar',
      headrest: true,
      armrests: '4D',
      seatDepthAdjust: true,
      mechanism: 'synchro-plus',
      ergoScore: 90,
      warrantyYears: 8,
    },
  },
]
