import type { Question } from '../../domain/types'

export const questions: Question[] = [
  {
    id: 'groesse',
    chip: 'Körpergröße',
    headline: 'Wie groß bist du?',
    sub: 'Sitzhöhe, Rückenlehne und Sitztiefe müssen zu deiner Körpergröße passen.',
    why: 'Jeder Stuhl hat einen Körpergrößenbereich, in dem die Verstellwege wirklich ausreichen. Außerhalb davon sitzt du dauerhaft zu hoch oder zu tief – das ist der häufigste Grund für Beschwerden trotz teurem Stuhl.',
    type: 'single',
    options: [
      { id: 'u165', label: 'Unter 165 cm' },
      { id: '165_178', label: '165 – 178 cm' },
      { id: '179_190', label: '179 – 190 cm' },
      { id: 'ue190', label: 'Über 190 cm' },
    ],
  },
  {
    id: 'gewicht',
    chip: 'Gewicht',
    headline: 'Wie viel wiegst du ungefähr?',
    sub: 'Wir rechnen mit Reserve zur Herstellerfreigabe.',
    why: 'Die angegebene Belastbarkeit ist ein Sicherheitswert, kein Komfortwert. Wer dauerhaft nahe am Limit sitzt, bekommt früher durchgesessene Polster und ausgeschlagene Mechaniken. Wir empfehlen deshalb nur Stühle mit Reserve.',
    type: 'single',
    options: [
      { id: 'u80', label: 'Bis 80 kg' },
      { id: '80_100', label: '80 – 100 kg' },
      { id: '100_120', label: '100 – 120 kg' },
      { id: 'ue120', label: 'Über 120 kg' },
    ],
  },
  {
    id: 'dauer',
    chip: 'Sitzdauer',
    headline: 'Wie lange sitzt du an einem normalen Arbeitstag?',
    sub: 'Nur die Zeit am Schreibtisch, nicht Feierabend auf dem Sofa.',
    why: 'Hersteller geben ihre Stühle für eine maximale tägliche Nutzungsdauer frei. Ein Modell für 6 Stunden ist bei 9 Stunden Schreibtischarbeit nicht nur unbequem – es verschleißt schneller und die Garantie greift oft nicht.',
    type: 'single',
    options: [
      { id: 'u3', label: 'Bis 3 Stunden' },
      { id: '3_6', label: '3 – 6 Stunden' },
      { id: '6_9', label: '6 – 9 Stunden' },
      { id: 'ue9', label: 'Mehr als 9 Stunden' },
    ],
  },
  {
    id: 'ruecken',
    chip: 'Rücken',
    headline: 'Wie geht es deinem Rücken?',
    sub: 'Ehrliche Antwort – davon hängt am meisten ab.',
    why: 'Bei beschwerdefreien Rücken zählt vor allem eine solide Grundergonomie. Bei bestehenden Beschwerden gewichten wir Lordosenstütze, Sitztiefenverstellung und Mechanik deutlich stärker – und schließen Modelle ohne verstellbare Rückenunterstützung aus.',
    type: 'single',
    options: [
      { id: 'keine', label: 'Keine Beschwerden', hint: 'Alles gut, ich will es so halten' },
      { id: 'verspannung', label: 'Gelegentliche Verspannungen', hint: 'Vor allem Nacken und Schultern' },
      { id: 'schmerzen', label: 'Regelmäßige Rückenschmerzen', hint: 'Mehrmals pro Woche' },
      { id: 'diagnose', label: 'Ärztliche Diagnose', hint: 'z. B. Bandscheibe, ISG, Skoliose' },
    ],
  },
  {
    id: 'ausstattung',
    chip: 'Muss haben',
    headline: 'Gibt es etwas, das unbedingt dabei sein muss?',
    sub: 'Mehrfachauswahl. Alles, was du hier wählst, behandeln wir als Ausschlusskriterium.',
    why: 'Diese Punkte filtern wir hart. Ein Stuhl ohne Kopfstütze taucht nicht als Empfehlung auf, wenn du eine Kopfstütze brauchst – auch wenn er sonst besser abschneidet.',
    type: 'multi',
    options: [
      { id: 'kopfstuetze', label: 'Kopfstütze', hint: 'Für Telefonate und Lehnpausen' },
      { id: 'armlehnen4d', label: '4D-Armlehnen', hint: 'Höhe, Breite, Tiefe, Winkel' },
      { id: 'sitztiefe', label: 'Sitztiefenverstellung', hint: 'Wichtig bei sehr langen oder kurzen Beinen' },
      { id: 'netz', label: 'Netzrücken', hint: 'Luftiger, wenn du schnell schwitzt' },
      { id: 'nichts', label: 'Nichts davon ist Pflicht', hint: 'Empfehlt mir einfach das Beste', exclusive: true },
    ],
  },
  {
    id: 'budget',
    chip: 'Budget',
    headline: 'Was möchtest du ungefähr ausgeben?',
    sub: 'Wir zeigen dir zusätzlich, was ein größeres Budget bringen würde.',
    why: 'Preis ist bei uns kein Rankingfaktor, sondern eine Grenze. Wir sortieren nicht nach Provision, sondern nach Passung – und sagen offen, wenn oberhalb deines Budgets ein deutlich besseres Modell steht.',
    type: 'single',
    options: [
      { id: 'u250', label: 'Bis 250 €' },
      { id: '250_450', label: '250 – 450 €' },
      { id: '450_700', label: '450 – 700 €' },
      { id: 'ue700', label: 'Über 700 €', hint: 'Qualität geht vor Preis' },
    ],
  },
]
